image: prom/prometheus
imageTag: v1.1.0
imageAlertManager: prom/alertmanager
imageTagAlertManager: v0.4.2

# Persist data to a persitent volume
persistence:
  enabled: true
  storageClass: generic
  size: 8Gi

extraargs:
    alertmanager.notification-queue-capacity :  10000

    #  Alert manager HTTP API timeout.
    alertmanager.timeout :  10s

    #  Comma-separated list of Alertmanager URLs to send notifications to.
    alertmanager.url : foobar

    #  Prometheus configuration file name.
    config.file :  prometheus.yml

