apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{template "fullname" .}}
  labels:
    heritage: {{.Release.Service | quote}}
    release: {{.Release.Name | quote}}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{template "fullname" .}}
        release: {{.Release.Name | quote}}
    spec:
      containers:
      - name: prometheus
        image: "{{.Values.image}}:{{.Values.imageTag}}"
        imagePullPolicy: {{default "Always" .Values.pullPolicy}}
        args:
          - "-alertmanager.notification-queue-capacity={{.Values.alertmanager_notification-queue-capacity}}"
          - "-alertmanager.timeout={{.Values.alertmanager_timeout}}"
          - "-alertmanager.url={{.Values.alertmanager_url}}"
          - "-config.file={{.Values.config_file}}"
          - "-log.format={{.Values.log_format}}"
          - "-log.level={{.Values.log_level}}"
          - "-query.max-concurrency={{.Values.query_max-concurrency}}"
          - "-query.staleness-delta={{.Values.query_staleness-delta}}"
          - "-query.timeout={{.Values.query_timeout}}"
          - "-storage.local.checkpoint-dirty-series-limit={{.Values.storage_local_checkpoint-dirty-series-limit}}"
          - "-storage.local.checkpoint-interval={{.Values.storage_local_checkpoint-interval}}"
          - "-storage.local.chunk-encoding-version={{.Values.storage_local_chunk-encoding-version}}"
          - "-storage.local.dirty={{.Values.storage_local_dirty}}"
          - "-storage.local.engine={{.Values.storage_local_engine}}"
          - "-storage.local.index-cache-size.fingerprint-to-metric={{.Values.storage_local_index-cache-size_fingerprint-to-metric}}"
          - "-storage.local.index-cache-size.fingerprint-to-timerange={{.Values.storage_local_index-cache-size_fingerprint-to-timerange}}"
          - "-storage.local.index-cache-size.label-name-to-label-values={{.Values.storage_local_index-cache-size_label-name-to-label-values}}"
          - "-storage.local.index-cache-size.label-pair-to-fingerprints={{.Values.storage_local_index-cache-size_label-pair-to-fingerprints}}"
          - "-storage.local.max-chunks-to-persist={{.Values.storage_local_max-chunks-to-persist}}"
          - "-storage.local.memory-chunks={{.Values.storage_local_memory-chunks}}"
          - "-storage.local.num-fingerprint-mutexes={{.Values.storage_local_num-fingerprint-mutexes}}"
          - "-storage.local.path={{.Values.storage_local_path}}"
          - "-storage.local.pedantic-checks={{.Values.storage_local_pedantic-checks}}"
          - "-storage.local.retention={{.Values.storage_local_retention}}"
          - "-storage.local.series-file-shrink-ratio={{.Values.storage_local_series-file-shrink-ratio}}"
          - "-storage.local.series-sync-strategy={{.Values.storage_local_series-sync-strategy}}"
          - "-storage.remote.graphite-address={{.Values.storage_remote_graphite-address}}"
          - "-storage.remote.graphite-prefix={{.Values.storage_remote_graphite-prefix}}"
          - "-storage.remote.graphite-transport={{.Values.storage_remote_graphite-transport}}"
          - "-storage.remote.influxdb-url={{.Values.storage_remote_influxdb-url}}"
          - "-storage.remote.influxdb.database={{.Values.storage_remote_influxdb_database}}"
          - "-storage.remote.influxdb.retention-policy={{.Values.storage_remote_influxdb_retention-policy}}"
          - "-storage.remote.influxdb.username={{.Values.storage_remote_influxdb_username}}"
          - "-storage.remote.opentsdb-url={{.Values.storage_remote_opentsdb-url}}"
          - "-storage.remote.timeout={{.Values.storage_remote_timeout}}"
          - "-web.console.libraries={{.Values.web_console_libraries}}"
          - "-web.console.templates={{.Values.web_console_templates}}"
          - "-web.enable-remote-shutdown={{.Values.web_enable-remote-shutdown}}"
          - "-web.external-url={{.Values.web_external-url}}"
          - "-web.listen-address={{.Values.web_listen-address}}"
          - "-web.route-prefix={{.Values.web_route-prefix}}"
          - "-web.telemetry-path={{.Values.web_telemetry-path}}"
          - "-web.user-assets={{.Values.web_user-assets}}"

        ports:
        - containerPort: 9090
        resources:
          requests:
            cpu: {{default "500m" .Values.Cpu}}
            memory: {{default "500M" .Values.Memory}}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
        - mountPath: /data
          name: storage-volume
      - name: alertmanager
        image: "{{.Values.imageAlertManager}}:{{.Values.imageTagAlertManager}}"
        imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
        args:
          - "-config.file=/etc/config/alertmanager.yml"
        resources:
          requests:
            cpu: {{default "100m" .Values.CpuAlertManager}}
            memory: {{default "50M" .Values.MemoryAlertManager}}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      - name: node-exporter
        image: "prom/node-exporter"
        imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
        resources:
          requests:
            cpu: {{default "50m" .Values.CpuNodeExporter}}
            memory: {{default "50M" .Values.MemoryNodeExporter}}
      volumes:
        - name: config-volume
          configMap:
            name: {{template "fullname" .}}
        - name: storage-volume
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{template "fullname" .}}
      {{- else }}
          emptyDir: {}
      {{- end -}}
